# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 https://pmckernin.github.io/
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pat McKernin
  
  email:             patrick@firstdraft.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
